# Shipped Configuration
# This file may be used as template for custom configuration
# custom configuration should be placed in:
#     "${XDG_CONFIG_HOME}/psprudence/config.yml"

# Special case
global:
  interval: 10
  persist: 5

charge:
  alert: Over Charging
  units: '%'
  min_warn: 90
  res_warn: 2
  probe_cmd: 'py: battery:charge'

discharge:
  alert: Discharging
  units: '%'
  min_warn: 20
  res_warn: 1
  reverse: true
  probe_cmd: 'py: battery:discharge'
  panic: 'py: battery:panic:10'

cpu:
  alert: CPU
  units: '%'
  min_warn: 80
  res_warn: 5
  probe_cmd: 'py: sensors:cpu'

load5:
  alert: 5 min load
  units: '%'
  min_warn: 75
  res_warn: 5
  probe_cmd: 'py: sensors:load:5'

load15:
  alert: 15 min load
  units: '%'
  min_warn: 50
  res_warn: 10
  probe_cmd: 'py: sensors:load:15'

memory:
  alert: memory
  units: '%'
  min_warn: 60
  res_warn: 10
  probe_cmd: 'py: sensors:memory'

temperature:
  alert: Core Temperature
  units: '°C'
  min_warn: 75
  res_warn: 5
  probe_cmd: 'py: sensors:temperature'
